#!/bin/sh -ex
#
# SingularInterface: A GAP interface to Singular
#
# Copyright of SingularInterface belongs to its developers.
# Please refer to the COPYRIGHT file for details.
#
# SPDX-License-Identifier: GPL-2.0-or-later


if [ ! -x singular/src/configure ] ; then
    (cd singular/src && ./autogen.sh)
fi

PREFIX=$PWD/singular/dst

mkdir -p $PREFIX
mkdir -p singular/build
cd singular/build
../src/configure --prefix=$PREFIX $@
