#!/bin/sh -ev

export CC="gcc -fpic -DPIC -DLIBSINGULAR"
export CXX="g++ -fpic -DPIC -DLIBSINGULAR"
export CFLAGS="-O0 -g"
export CXXFLAGS="-O0 -g"

cd Singular

./configure --without-dynamic-kernel --without-MP
#./configure --without-dynamic-kernel --without-MP --without-omalloc

SINGARCHNAME=`./singuname.sh`
echo $SINGARCHNAME > ../SINGARCHNAME

# HACK: On OS X, try using the Fink GMP, if present
if [ `uname` = "Darwin" ] ; then
    if [ -f /sw/include/gmp.h ] ; then
        rm -f $SINGARCHNAME/include/gmp.h
        rm -f $SINGARCHNAME/lib/libgmp.dylib
        ln -s /sw/include/gmp.h $SINGARCHNAME/include
        ln -s /sw/lib/libgmp.dylib $SINGARCHNAME/lib
    fi
fi
