#!/bin/sh -ev

export CC="gcc -fpic -DPIC -DLIBSINGULAR"
export CXX="g++ -fpic -DPIC -DLIBSINGULAR"
export CFLAGS="-O0 -g"
export CXXFLAGS="-O0 -g"

cd Singular

make install-libsingular

# Install missing header (required for Singular 3-1-6)
#cp Singular/sing_dbm.h `./singuname.sh`/include/singular/

# HACK
if [ `uname` = "Darwin" ] ; then
    echo "Setting libsingular.dylib load path (because of Mac OS X)"
    install_name_tool -id $PWD/Singular/libsingular.dylib Singular/libsingular.dylib
fi

