name: SingularInterface
version: 0.7.2
date: 2014-11-01
description: |
    A GAP interface to Singular

authors:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Max Horn
      url: http://www.quendi.de/math
    - name: Frank Lübeck
      url: http://www.math.rwth-aachen.de/~Frank.Luebeck/
    - name: Oleksandr Motsak
      url: http://www.mathematik.uni-kl.de/~motsak/
    - name: Max Neunhoeffer
      url: http://www-groups.msc.st-andrews.ac.uk/~neunhoef
    - name: Hans Schoenemann
      url: http://www.mathematik.uni-kl.de/~hannes/

maintainers:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Max Horn
      url: http://www.quendi.de/math
    - name: Frank Lübeck
      url: http://www.math.rwth-aachen.de/~Frank.Luebeck/

GAP: ">=4.7.2"

suggested-pkgs:
    - name: "GAPDoc"
      version: "1.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "AutoDoc"
      version: "2014.03.27"
      url: "https://gap-packages.github.io/AutoDoc"

www: http://gap-system.github.io/SingularInterface
readme: README
packageinfo: http://gap-system.github.io/SingularInterface/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-system/SingularInterface/releases/download/v0.7.2/SingularInterface-0.7.2.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-system/SingularInterface/releases/download/v0.7.2/SingularInterface-0.7.2.tar.bz2

abstract: |
    The <span class="pkgname">SingularInterface</span> package provides  a GAP interface to Singular, enabling direct access to the complete  functionality of Singular.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
