s := SI_ring(3,["a","b"],[["dp",2]]);
p := SI_matrix(1,1,s,"a+b+ab");
SI_\[(p,1);
SI_\[(p,2);
SI_\[(p,3);
SI_\[(p,4);
m := SI_matrix(2,2,s,"a,b,ab,2");
SI_\[(m,1,1);
SI_\[(m,2,1);
SI_\[(m,2,2);
SI_\*(m,2);
SI_\*(m,0);
a := SI_poly(s,"a");
SI_\*(m,a);
Display(m);
SI_\-(m,m);
SI_\-(m);
