// DO NOT EDIT THIS FILE BY HAND IT IS MACHINE GENERATED
  {"_SI_p_String", 1,
  "TODO", Func_SI_p_String,
  "lowlevel_mappings.cc:Func_SI_p_String" },

  {"_SI_p_Neg", 1,
  "TODO", Func_SI_p_Neg,
  "lowlevel_mappings.cc:Func_SI_p_Neg" },

  {"_SI_pp_Mult_qq", 2,
  "TODO", Func_SI_pp_Mult_qq,
  "lowlevel_mappings.cc:Func_SI_pp_Mult_qq" },

  {"_SI_pp_Mult_nn", 2,
  "TODO", Func_SI_pp_Mult_nn,
  "lowlevel_mappings.cc:Func_SI_pp_Mult_nn" },

  {"_SI_p_Add_q", 2,
  "TODO", Func_SI_p_Add_q,
  "lowlevel_mappings.cc:Func_SI_p_Add_q" },

  {"_SI_p_Minus_mm_Mult_qq", 3,
  "TODO", Func_SI_p_Minus_mm_Mult_qq,
  "lowlevel_mappings.cc:Func_SI_p_Minus_mm_Mult_qq" },

  {"_SI_p_Plus_mm_Mult_qq", 3,
  "TODO", Func_SI_p_Plus_mm_Mult_qq,
  "lowlevel_mappings.cc:Func_SI_p_Plus_mm_Mult_qq" },

