// DO NOT EDIT THIS FILE BY HAND IT IS MACHINE GENERATED
#ifdef __cplusplus
extern "C" {
#endif /* ifdef __cplusplus */

Obj Func_SI_p_String(Obj self, Obj arg1);
Obj Func_SI_p_Neg(Obj self, Obj arg1);
Obj Func_SI_pp_Mult_qq(Obj self, Obj arg1, Obj arg2);
Obj Func_SI_pp_Mult_nn(Obj self, Obj arg1, Obj arg2);
Obj Func_SI_p_Add_q(Obj self, Obj arg1, Obj arg2);
Obj Func_SI_p_Minus_mm_Mult_qq(Obj self, Obj arg1, Obj arg2, Obj arg3);
Obj Func_SI_p_Plus_mm_Mult_qq(Obj self, Obj arg1, Obj arg2, Obj arg3);

#ifdef __cplusplus
}
#endif /* ifdef __cplusplus */
