// DO NOT EDIT THIS FILE BY HAND IT IS MACHINE GENERATED
  {"SI_p_String", 1,
  "TODO", FuncSI_p_String,
  "lowlevel_mappings.cc:FuncSI_p_String" },

  {"SI_p_Add_q", 2,
  "TODO", FuncSI_p_Add_q,
  "lowlevel_mappings.cc:FuncSI_p_Add_q" },

  {"SI_p_Neg", 1,
  "TODO", FuncSI_p_Neg,
  "lowlevel_mappings.cc:FuncSI_p_Neg" },

  {"SI_pp_Mult_qq", 2,
  "TODO", FuncSI_pp_Mult_qq,
  "lowlevel_mappings.cc:FuncSI_pp_Mult_qq" },

  {"SI_pp_Mult_nn", 2,
  "TODO", FuncSI_pp_Mult_nn,
  "lowlevel_mappings.cc:FuncSI_pp_Mult_nn" },

